services:
  redundafier:
    container_name: redundafier
    build: .
    platform: linux/amd64
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 1336
      IS_FORWARDED_SERVER_ON_SAME_DOCKER: 1
    networks:
      - cards_net
    ports:
      - "1336:1336"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "npm install &&
             npm run dev"

volumes:
  node_modules:

networks:
  cards_net:
    name: cards_network
    external: true