services:
  app:
    container_name: redundafier
    build: .
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 1336
      IS_FORWARDED_SERVER_ON_SAME_DOCKER: 1
    ports:
      - "1336:1336"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  node_modules:
