services:
  app:
    extends:
      file: ../docker-compose.yml
      service: app
    # Override command to ensure container stays running
    command: sleep infinity
    environment:
      # Additional dev-specific environment variables can be added here
      NODE_ENV: development
    volumes:
      - type: bind
        source: ..
        target: /app
      - type: volume
        target: /app/node_modules

volumes:
  node_modules:
